// General Types
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// Kategori Types
export const GET_KATEGORIES = 'GET_KATEGORIES'
export const GET_KATEGORI = 'GET_KATEGORI'
export const KATEGORIES_ERROR = 'KATEGORIES_ERROR'
export const ADD_KATEGORI_ERROR = 'ADD_KATEGORI_ERROR';

// Subkategori Types
export const GET_SUBKATEGORIES = 'GET_SUBKATEGORIES';
export const GET_SUBKATEGORI = 'GET_SUBKATEGORI';
export const ADD_SUBKATEGORI_ERROR = 'ADD_KATEGORI_ERROR';
export const GET_ALL_SUBKATEGORIES = 'GET_ALL_SUBKATEGORIES';
export const UPDATE_SUBKATEGORI_ERROR = 'UPDATE_SUBKATEGORI_ERROR';
export const DELETE_SUBKATEGORI_ERROR = 'DELETE_SUBKATEGORI_ERROR';