// General Types
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// Kategori Types
export const GET_KATEGORIES = 'GET_KATEGORIES'
export const GET_KATEGORI = 'GET_KATEGORI'
export const KATEGORIES_ERROR = 'KATEGORIES_ERROR'
export const ADD_KATEGORI_ERROR = 'ADD_KATEGORI_ERROR';

// Subkategori Types
export const GET_SUBKATEGORIES = 'GET_SUBKATEGORIES';
export const GET_SUBKATEGORI = 'GET_SUBKATEGORI';
export const ADD_SUBKATEGORI_ERROR = 'ADD_KATEGORI_ERROR';
export const GET_ALL_SUBKATEGORIES = 'GET_ALL_SUBKATEGORIES';
export const UPDATE_SUBKATEGORI_ERROR = 'UPDATE_SUBKATEGORI_ERROR';
export const DELETE_SUBKATEGORI_ERROR = 'DELETE_SUBKATEGORI_ERROR';
export const GET_SUBKATEGORIES_BY_CATEGORY = 'GET_SUBKATEGORIES_BY_CATEGORY';

// Product Types
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

// Supplier Types
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR';
export const UPDATE_SUPPLIER_ERROR = 'UPDATE_SUPPLIER_ERROR';
export const DELETE_SUPPLIER_ERROR = 'DELETE_SUPPLIER_ERROR';
export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';
